channel: "stable"
timestamp_unix: 1765614016
components {
  name: DESKTOP
  version: "0.5.239"
  package_url: "packages/desktop-0.5.239.exe"
  sha256: "\x7e\x56\xa5\x09\x13\x8d\x7e\x2b\xd0\xb7\xf3\x36\x62\x97\x74\x57\xef\x88\x7e\xf0\x7a\x7f\x19\xd8\x57\x9f\x26\x52\xe0\xb8\x66\x24"
  size: 1740800
  install {
    target: "bin/TagPulse.exe"
    type: "replace"
  }
}
components {
  name: SERVICE
  version: "0.5.239"
  package_url: "packages/service-0.5.239.exe"
  sha256: "\xa2\x03\xb4\x3f\xa8\xd9\x6e\x10\xab\xdb\x25\x92\x36\x14\xf4\xd1\xb3\xb9\x21\x62\x6e\xd6\x86\x6e\x32\x28\x96\x29\x76\xcc\x54\x1f"
  size: 13701632
  install {
    target: "bin/TagPulseService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: LHM
  version: "0.5.239"
  package_url: "packages/lhm-0.5.239.exe"
  sha256: "\x0a\xd8\xb5\xf2\xce\xb4\xf4\x97\xea\x9f\x01\x2f\xde\x53\x72\xf1\x7f\x5f\xc0\xd7\x58\x53\x7b\xa7\xb4\x8b\x2e\xd3\x47\xdf\x8f\xec"
  size: 72432457
  install {
    target: "bin/TagPulseLHMService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: UPDATER
  version: "0.5.239"
  package_url: "packages/updater-0.5.239.exe"
  sha256: "\xcf\xa6\x6a\x68\xf3\x61\xed\x86\x3b\x34\x30\xe6\x8c\xa3\x3c\x12\xfb\xb1\x6a\x19\x3f\xd8\xc6\x9e\xfc\x59\x70\x4b\xac\xc1\xb6\x6e"
  size: 1716224
  install {
    target: "bin/TagPulseUpdater.exe"
    type: "replace"
  }
}
components {
  name: UI
  version: "0.5.239"
  package_url: "packages/ui-0.5.239.zip"
  sha256: "\xf5\xed\x79\xe0\x9a\x0a\x83\x39\xed\x75\xce\xe7\x75\x61\x04\xef\x53\xe4\x03\x93\x58\x54\x0d\xd8\x57\x93\x83\x5d\x5d\x90\x24\x4c"
  size: 2403333
  install {
    target: "ui"
    type: "unzip-replace"
    reload_ui: true
  }
}
