channel: "stable"
timestamp_unix: 1773414422
components {
  name: DESKTOP
  version: "0.6.143"
  package_url: "packages/desktop-0.6.143.exe"
  sha256: "\x76\xc9\x96\x2c\x54\xbd\xb5\x83\x16\x2e\x02\x51\xff\x80\xc6\x37\xc1\xf2\x42\xba\x82\xe2\x7b\xcb\x99\xed\x5c\x9d\x05\xb6\x50\xb9"
  size: 1968640
  install {
    target: "bin/TagPulse.exe"
    type: "replace"
  }
}
components {
  name: SERVICE
  version: "0.6.143"
  package_url: "packages/service-0.6.143.exe"
  sha256: "\x21\x89\x32\x3b\xb5\x20\x65\x50\xa7\x10\x9d\x5a\xee\x9e\x98\x28\x8f\xec\xb5\x5e\x0e\x17\x44\x4d\x47\xd8\xd3\xc5\x73\x34\x24\x58"
  size: 15565824
  install {
    target: "bin/TagPulseService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: LHM
  version: "0.6.143"
  package_url: "packages/lhm-0.6.143.exe"
  sha256: "\xe4\xde\xf0\x56\xb1\x50\xd7\x70\x56\x89\x26\x23\x6b\xf3\x78\x3d\x9b\x92\x38\x94\x45\x38\x90\x96\xe2\x77\xbd\x4b\x54\x6e\x86\x1d"
  size: 73755651
  install {
    target: "bin/TagPulseLHMService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: UPDATER
  version: "0.6.143"
  package_url: "packages/updater-0.6.143.exe"
  sha256: "\x5f\x73\x74\x33\x26\x3b\x7e\x74\x2a\x09\x1a\xd7\xc1\x4c\xb1\xff\xac\x73\x8b\xfe\x4f\x02\xfa\xd7\xe0\xc6\xce\xa8\x11\x36\xf5\x8f"
  size: 2157568
  install {
    target: "bin/TagPulseUpdater_v2.exe"
    type: "replace"
  }
}
components {
  name: UI
  version: "0.6.143"
  package_url: "packages/ui-0.6.143.zip"
  sha256: "\x6f\x4b\xed\x42\xc2\x9c\xda\xa0\x47\xca\xfc\x65\x5d\x2c\xfe\x6b\xca\x5c\x7a\x3c\x0d\x0a\x22\x74\xea\xfd\x1d\xe9\x49\xed\xb0\xaa"
  size: 3454250
  install {
    target: "ui"
    type: "unzip-replace"
    reload_ui: true
  }
}
