channel: "stable"
timestamp_unix: 1764391912
components {
  name: DESKTOP
  version: "0.5.134"
  package_url: "packages/desktop-0.5.134.exe"
  sha256: "\x64\x52\x5a\x3b\xaa\x34\xc7\xab\xe8\x42\xdb\xd3\x3d\x70\x2e\xb9\xf7\x91\xe2\x36\x57\x23\xd0\xa4\x4c\x15\x32\x80\xac\x45\xdc\xc3"
  size: 1620480
  install {
    target: "bin/TagPulse.exe"
    type: "replace"
  }
}
components {
  name: SERVICE
  version: "0.5.134"
  package_url: "packages/service-0.5.134.exe"
  sha256: "\xfc\xb8\x89\x46\xff\xa8\x96\xb6\xc3\xfd\xf4\x2d\x68\x69\x69\xc4\xc6\xd7\x5f\xe2\x24\x4c\x18\x0c\xc3\x1f\x85\x44\x3d\x33\xca\x69"
  size: 12420096
  install {
    target: "bin/TagPulseService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: LHM
  version: "0.5.134"
  package_url: "packages/lhm-0.5.134.exe"
  sha256: "\xa8\x42\xc0\x3c\x09\x90\x81\xd3\x3f\x35\x76\xba\xf4\x46\xfd\x74\x84\x06\x8e\x9d\x71\xe7\xab\xa4\xe3\x7f\x56\xf0\x36\x91\x9f\x4b"
  size: 72432457
  install {
    target: "bin/TagPulseLHMService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: UPDATER
  version: "0.5.134"
  package_url: "packages/updater-0.5.134.exe"
  sha256: "\x92\x95\x16\x41\xf9\x8c\xd8\x14\x28\x71\x74\x2e\x3b\x9e\x25\x6e\x46\x76\x7e\xbd\xd7\xc0\x6f\x9b\x35\x49\x66\xaa\xad\x2d\x70\x36"
  size: 1619456
  install {
    target: "bin/TagPulseUpdater.exe"
    type: "replace"
  }
}
components {
  name: UI
  version: "0.5.134"
  package_url: "packages/ui-0.5.134.zip"
  sha256: "\xa3\x5e\xca\x40\x20\x18\xa6\x87\x39\xa0\xfc\xa1\xcf\xd8\x00\x0b\x75\x1d\xf1\x61\x22\x5e\xe7\x97\x76\xe2\x04\x6e\xb0\xfe\x87\x85"
  size: 1444396
  install {
    target: "ui"
    type: "unzip-replace"
    reload_ui: true
  }
}
