channel: "beta"
timestamp_unix: 1790417335
components {
  name: DESKTOP
  version: "0.7.5b"
  package_url: "packages/desktop-0.7.5b.exe"
  sha256: "\xc1\xd9\xe1\xef\xb9\x41\xb2\xdc\x6c\x7d\x7d\x79\x84\x01\xdc\xfe\x30\xf4\x11\x1c\xc0\xee\xe8\xcc\xc3\x49\x0a\xe5\xe5\x9b\x52\x47"
  size: 2387680
  install {
    target: "bin/TagPulse.exe"
    type: "replace"
  }
}
components {
  name: SERVICE
  version: "0.7.5b"
  package_url: "packages/service-0.7.5b.exe"
  sha256: "\xab\xc9\xec\x16\x65\xe9\xe8\x40\x01\x65\x56\xe8\x60\xaa\x89\x4f\x84\x80\x99\xbd\x31\x15\xf2\xe5\x7c\xb4\x3e\x2c\xc3\xc7\xbe\x78"
  size: 17173216
  install {
    target: "bin/TagPulseService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: LHM
  version: "0.7.5b"
  package_url: "packages/lhm-0.7.5b.exe"
  sha256: "\xdd\xf8\xac\x5e\xdb\x0a\x36\x08\xb7\xf4\x89\xcf\xb2\x03\x84\x45\x84\x84\x5a\x2e\x8a\xf4\xf7\xe3\xf0\x61\xbe\x92\x7b\xa8\x2c\x46"
  size: 73696552
  install {
    target: "bin/TagPulseLHMService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: UPDATER
  version: "0.7.5b"
  package_url: "packages/updater-0.7.5b.exe"
  sha256: "\x04\x18\xee\x2e\x4f\x77\xe4\xbd\xe0\x73\x25\x0e\x8b\xf9\x94\xdd\x62\x9f\x59\x29\x66\x71\xab\x3a\xf2\x92\x95\xd8\x3f\xaa\x05\x91"
  size: 2577632
  install {
    target: "bin/TagPulseUpdater_v2.exe"
    type: "replace"
  }
}
components {
  name: UI
  version: "0.7.5b"
  package_url: "packages/ui-0.7.5b.zip"
  sha256: "\xcf\xb5\xd7\x1b\x92\x83\xf8\x4c\xcc\xa5\xa0\x68\xcd\x5b\x44\xdb\x3e\x99\x85\x7f\x36\x82\x6f\x33\x8c\xa5\x91\x42\x59\xb7\xfe\xb5"
  size: 2026843
  install {
    target: "ui"
    type: "unzip-replace"
    reload_ui: true
  }
}
