channel: "beta"
timestamp_unix: 1787328505
components {
  name: DESKTOP
  version: "0.6.223b"
  package_url: "packages/desktop-0.6.223b.exe"
  sha256: "\x7c\x83\x0d\x2b\xca\x6e\x62\xe5\xfc\xf9\xce\x9e\x8e\xd7\x71\x9b\x74\x1a\x56\x3e\xb3\x21\xfa\x6f\xb8\x0e\xf9\x54\xab\x19\xe8\x4b"
  size: 2151648
  install {
    target: "bin/TagPulse.exe"
    type: "replace"
  }
}
components {
  name: SERVICE
  version: "0.6.223b"
  package_url: "packages/service-0.6.223b.exe"
  sha256: "\x0c\x32\x8d\xd1\x7d\xe0\x00\x85\x95\x2f\x3e\xa7\x6f\x8d\xdf\x0b\xb9\x47\x07\xbd\x65\x54\xdf\x07\x09\x52\x52\x12\x64\x91\x9c\x80"
  size: 16261856
  install {
    target: "bin/TagPulseService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: LHM
  version: "0.6.223b"
  package_url: "packages/lhm-0.6.223b.exe"
  sha256: "\x93\x84\xaa\x37\x0c\xeb\x73\xfc\xbb\x3c\x22\xbb\x32\x3e\x8a\xe2\x70\x2d\x04\x56\x1b\x56\xf6\x76\xf4\x58\xa5\xf8\x9e\x1f\x00\xe8"
  size: 73680448
  install {
    target: "bin/TagPulseLHMService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: UPDATER
  version: "0.6.223b"
  package_url: "packages/updater-0.6.223b.exe"
  sha256: "\x51\x70\xd9\x09\xb9\x38\xcf\xef\x8f\xb3\xa0\x31\x21\x8b\x11\xa4\x11\x66\x2a\xdf\xd2\x94\xcc\xcd\x02\x73\x18\xff\xe4\xd6\x43\x0e"
  size: 2318048
  install {
    target: "bin/TagPulseUpdater_v2.exe"
    type: "replace"
  }
}
components {
  name: UI
  version: "0.6.223b"
  package_url: "packages/ui-0.6.223b.zip"
  sha256: "\x15\xa7\x17\x13\xdd\x78\xfe\x3e\x30\x49\xd8\xe7\x82\xea\xc2\x73\x88\x3e\xfc\x35\x7d\xe4\x35\x1b\x3d\x88\xf3\x5e\xcc\x13\xb1\xd7"
  size: 2663545
  install {
    target: "ui"
    type: "unzip-replace"
    reload_ui: true
  }
}
