channel: "beta"
timestamp_unix: 1768912120
components {
  name: DESKTOP
  version: "0.6.74b"
  package_url: "packages/desktop-0.6.74b.exe"
  sha256: "\x7e\x47\x20\xa4\x3c\xef\x70\x19\x93\x59\xc0\x52\xce\xcc\xc8\x38\x46\xd7\xeb\x22\x2e\x0b\x9e\x07\xae\xe9\xdd\x57\xd9\xe0\x54\xda"
  size: 1849856
  install {
    target: "bin/TagPulse.exe"
    type: "replace"
  }
}
components {
  name: SERVICE
  version: "0.6.74b"
  package_url: "packages/service-0.6.74b.exe"
  sha256: "\xe0\x9d\x0c\xd0\xa6\xfa\xc2\x12\x3d\x14\xe5\x2f\xd6\xbc\xf5\x57\xfd\xc9\x1f\x70\x23\xe5\x3a\x8c\x3b\x87\xad\x15\x4e\x59\xf2\x0e"
  size: 14751232
  install {
    target: "bin/TagPulseService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: LHM
  version: "0.6.74b"
  package_url: "packages/lhm-0.6.74b.exe"
  sha256: "\xba\xe3\x20\xcc\x85\xd6\xcf\x44\x93\x10\x86\x08\x95\x72\x84\x52\xfa\xcc\x39\x02\xba\x74\xa7\xb9\xdc\x1d\xdb\xd6\x0e\x87\xb8\xfa"
  size: 73763841
  install {
    target: "bin/TagPulseLHMService.exe"
    type: "replace"
    stop_services: "TagPulseService"
    start_services: "TagPulseService"
  }
}
components {
  name: UPDATER
  version: "0.6.74b"
  package_url: "packages/updater-0.6.74b.exe"
  sha256: "\xee\x0e\x99\xaf\xaa\xb6\xc2\xae\xb2\xf7\x6b\x53\xa4\x55\xf7\xa9\xd4\x47\x94\x35\x62\x2e\xaa\xb5\x8d\x69\x22\x07\x64\xde\x1f\x77"
  size: 2009600
  install {
    target: "bin/TagPulseUpdater_v2.exe"
    type: "replace"
  }
}
components {
  name: UI
  version: "0.6.74b"
  package_url: "packages/ui-0.6.74b.zip"
  sha256: "\xd0\xb0\xe3\x00\x43\x3a\x02\xe2\xf3\xac\x70\x4f\x66\xbe\x99\x86\x2e\x19\x3f\x4e\xe0\x0d\xee\x1a\x38\xa1\xea\x0e\x35\x9e\x38\x09"
  size: 3157062
  install {
    target: "ui"
    type: "unzip-replace"
    reload_ui: true
  }
}
